name: Deploy Site

on: 

  push:

    branches:
      
      - main

jobs:

  deploy-site:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout the current code
        uses: actions/checkout@v2

      - name: Build react app to static site
        run: |
          git checkout pages
          cd verble
          npm install
          CI="" npm run build
          mv build/* ../
          cd ..
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add *
          git commit -m "Build"
          git push --set-upstream -f origin pages 
          
