name: Deploy Site

on: 

  push:

    branches:
      
      - main

jobs:

  deploy-site:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout the current code
        uses: actions/checkout@v2

      - name: Build react app to static site
        run: |
          git fetch --all
          git checkout pages
          git reset --hard origin/main
          cd verble
          npm install
          CI="" npm run build
          mv -f build/* ../
          cd ..
          git config --global user.email "repo@this.com"
          git config --global user.name "the repo"
          git add *
          git commit -m "Build"
          git push -f --set-upstream origin pages
