name: Deploy Site

on: 

  push:

    branches:
      
      - main

jobs:

  deploy-site:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout the current code
        uses: actions/checkout@v2

      - name: Build react app to static site
        run: |
          cd verble
          npm install
          CI="" npm run build

      - name: Push to pages branch
        run: |
          git add -f build
          git push -f origin pages